version: "3.7"

services:
  nginx:
    image: nginx:1.20.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
  django:
    build:
      context: .
      network: host
    command: gunicorn --bind 0.0.0.0:8000 snugg.wsgi
    expose:
      - "8000"
