# Generated by Django 4.0.2 on 2022-07-20 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directory",
            name="filenames",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=256), default=["index"], size=20
            ),
            preserve_default=False,
        ),
    ]
