# Generated by Django 4.0.2 on 2022-07-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0002_post_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="accepted_answer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin",
                to="qna.answer",
            ),
        ),
    ]
