# Generated by Django 4.0.2 on 2022-03-09 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majors",
                        to="univ.college",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email_host", models.CharField(blank=True, max_length=30)),
                ("logo_image", models.ImageField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="UnivProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_year", models.IntegerField(null=True)),
                ("graduated", models.BooleanField(null=True)),
                (
                    "degree",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("U", "undergraduate"),
                            ("A", "associate"),
                            ("B", "bachelor"),
                            ("M", "master"),
                            ("D", "doctor"),
                        ],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "college",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="univ.college",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="univ.major",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="univ.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="university",
            name="members",
            field=models.ManyToManyField(
                through="univ.UnivProfile", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="major",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="majors",
                to="univ.university",
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colleges",
                to="univ.university",
            ),
        ),
    ]
