# Generated by Django 4.0.2 on 2022-05-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("univ", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("lecture_id", models.CharField(max_length=20)),
                ("instructor", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2022)),
                (
                    "season",
                    models.IntegerField(
                        choices=[
                            (1, "Winter"),
                            (2, "Spring"),
                            (3, "Summer"),
                            (4, "Fall"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-season"),
            },
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("year", "season"), name="unique_semester"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="agora.lecture",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agora_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="college",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lectures",
                to="univ.college",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="major",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lectures",
                to="univ.major",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="semesters",
            field=models.ManyToManyField(related_name="lectures", to="agora.Semester"),
        ),
        migrations.AddField(
            model_name="lecture",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lectures",
                to="univ.university",
            ),
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("lecture_id", "university"), name="unique_lecture"
            ),
        ),
    ]
