name: Django CD
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run deploy scripts on server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        script: |
          sh deploy
