name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      psql:
        image: postgres:12
        env:
          TZ: Asia/Seoul
          POSTGRES_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRESQL_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRESQL_NAME }}
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3

    - name: create dotenv
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > ./.env
        echo -e "\n${{ secrets.DOTENV }}" >> ./.env

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py migrate
        python manage.py test
